[package]
name = "hikari-database"
version = "0.1.0"
edition = "2024"

[dependencies]
hikari-utils = { path = "../utils" }
sqlx = { version = "0.9.0", features = ["postgres", "runtime-tokio", "macros", "uuid", "chrono"] }
tokio = { version = "1.53.1", features = ["sync", "macros"] }
thiserror = "2.0.20"
twilight-model = "0.17.1"
uuid = { version = "1.26.0", features = ["v4", "serde"] }
chrono = { version = "0.4.45", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
