[build]
rustflags = ["-C", "target-cpu=native"]

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "split-debuginfo=unpacked", "-C", "target-cpu=native"]

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "target-cpu=native"]

[target.'cfg(target_os = "windows")']
rustflags = ["-C", "target-cpu=native"]

[env]
RUST_BACKTRACE = "1"
